### ISSUE TITLE
Feature Request: Configurable comparator function

### ISSUE THREAD

**Issue by Ghost---Shadow** [google-research/fast-soft-sort#1]
This is good. 

Is there a way to configure the comparator function?

My plan was to have a neural network as the comparator function and it would learn from already sorted/ranked sequences.

**Comment by mblondel** [comment]
It's not entirely clear how we could do that with our isotonic regression based approach. Where would you insert the comparator function?

**Comment by Ghost---Shadow** [comment]
Something like this. I implemented Bubble sort with a learnable comparator function

https://github.com/Ghost---Shadow/differentiable-programming-handbook/blob/master/notebooks/bubble-sort.ipynb

**Comment by mblondel** [comment]
It's easy to do for bubble sort, not so obvious for our isotonic regression based approach. I don't think we'll be able to implement this so I'm closing the issue.
