### ISSUE TITLE
Moving isotonic to thirdparty broke the python setup.py install

### ISSUE THREAD

**Issue by AdrienCorenflos** [google-research/fast-soft-sort#3]
@mblondel 

That's because you didn't add the thirdparty module explicitly in the setup, or alternatively add a __init__.py in the thirdparty folder to make it a subpackage.

I'll send a PR with the second solution.

Adrien

**Comment by mblondel** [comment]
Fixed in 8358976435e2f57aaae443eb32601810bb4b769d.
